var names00 = [ 
	'Block Phaser', 
	'Large Capture Block',
	'Medium Capture Block',
	'Small Capture Block',
	'Checkpoint',
	'(arctek book / recipe?)',
	'Delay Gate',
	'Flare',
	'Flip-Flop Gate',
	'Inverter Gate',
	'Logic Gate',
	'Number Comparison Gate',
	'Number Pad',
	'(diamond?)',
	'Pressure Plate',
	'Sensor',
	'Arc Sign',
	'Loot Spawner',
	'Mob Spawner',
	'(arcstone?)',
	'Switch',
	'Wiring Tool',
	'Adventure Gate',
	'Arcstone',
	'Diamond Armguards',
	'Iron Armguards',
	'Leather Armguards',
	'Lumite Armguards',
	'Obsidian Armguards',
	'Stone Weapon Rack',
	'Asphalt',
	'Candy Skull Banner',
	'Iron Bars',
	'(azure beacon?)',
	'Healing Beacon',
	'Blue Beacon',
	'(some liquid container?)',
	'Red Beacon',
	'White Beacon',
	'Yellow Beacon',
	'(bed frame?)',
	'Galactic Sleep Pod',
	'Bed',
	'Blue Bed',
	'Red Bed',
	'Yellow Bed',
	'Bedrock',
	'Beeswax',
	'Queen Bee',
	'Industrial Bellows',
	'Block of Goo',
	'Orange Block of Goo',
	'Purple Block of Goo',
	'Shredded Leaves',
	'(three orange blocks?)',
	'Bone',
	'Wood Book Shelf',
	'Bosshog Tusk',
	'Bow Tie',
	'Blue Bow Tie',
	'Red Bow Tie',
	'Yellow Bow Tie',
	'Bread',
	'Blazing Bread',
	'Bog Bread',
	'Corrupted Bread',
	'Gingerbread Loaf',
	'Tar Bread',
	'Wholesome Bread',
	'Diamond Breastplate',
	'Iron Breastplate',
	'Leather Breastplate',
	'Lumite Breastplate',
	'Obsidian Breastplate',
	'Cactus',
	'Campfire',
	'Pumpkiru Candy',
	'Candy Skull Statue',
	'Ruddy Canyonstone',
	'Canyonstone',
	'Dark Canyonstone',
	'Industrial Chimney',
	'Laurel Bedrock Wall',
	'(sun bedrock wall?)',
	'Blue Carpet',
	'Red Carpet',
	'Yellow Carpet',
	'Cattails',
	'Medieval Chain',
	'(bedrock / limestone chair?)',
	'Diamond Chair',
	'Iron Chair',
	'Lumite Chair',
	'Hidden Temple Chair',
	'Medieval Chair',
	'Obsidian Chair',
	'Galactic Captain\'s Chair',
	'Stone Chair',
	'Wood Chair',
	'Medieval Chandelier',
	'Arctek Chest',
	'Grand Arctek Chest',
	'(gift boxes?)',
	'Industrial Locker',
	'Medieval Chest',
	'Pumpkin Treasure Chest',
	'Pumpkin Chest',
	'Pumpkiru\'s King Treasure Chest',
	'Pumpkiru\'s King Chest',
	'(login bundle chest?)',
	'Royal Pumpkin Treasure Chest',
	'Royal Pumpkin Chest',
	'Stone Chest',
	'(treasure chest?)',
	'(yellow treasure chest?)',
	'(blue treasure chest?)',
	'(purple treasure chest?)',
	'(green treasure chest?)',
	'(red treasure chest?)',
	'Wood Chest',
	'Gingerbread Chimney',
	'Industrial Smoke Stack',
	'Blizzard Chizzard Gizzard',
	'Feather',
	'Chizzard Gizzard',
	'(map?)',
	'Coal',
	'Coal Node',
	'Shredded Leaves Column',
	'Corrupted Stone Column',
	'Diamond Column',
	'Hardened Lava Column',
	'Igneous Column',
	'Lumite Column',
	'Iron Column',
	'Obsidian Column',
	'Bedrock Column',
	'Limestone Column',
	'Spiral Limestone Column',
	'Spiral Limestone Column (round)',
	'Straight Limestone Column',
	'Straight Limestone Column (round)',
	'(vertical stripes?)',
	'Stacked Stone Column',
	'Thatched Column',
	'Wood Column',
	'Blue Wood Column',
	'Red Wood Column',
	'Yellow Wood Column',
	'Crash Dump',
	'Blue Concrete',
	'(gray concrete?)',
	'Red Concrete',
	'Yellow Concrete',
	'Galactic Grav-Chamber',
	'Coral',
	'Corruption Dust',
	'Taming Collar',
	'(bundle crate?)',
	'Infused Crystal',
	'(green crystal?)',
	'Crystal Shard',
	'Death Statue',
	'(missing icon?)',
	'Diamond Bar',
	'Dirt',
	'Corrupted Dirt',
	'(tilled / plowed land?)',
	'Iron Bar Door',
	'Bungalow Door',
	'Rustic Wood Door',
	'Diamond Door',
	'Gingerbread Door',
	'Industrial Door',
	'Bedrock Door',
	'Lumite Door',
	'Hidden Temple Door',
	'Medieval Door',
	'Obsidian Door',
	'Galactic Bay Door',
	'Stone Door',
	'Wood Door',
	'Haunted Door',
	'Dustevil Dust',
	'Blue Pigment',
	'Red Pigment',
	'Yellow Pigment',
	'Blizzard Chizzard Egg',
	'Chizzard Egg',
	'Excavator',
	'Advanced Excavator',
	'Super Excavator',
	'Advanced Extractor',
	'Extractor',
	'(extractor prototype?)',
	'Super Extractor',
	'Fan',
	'Industrial Fan',
	'Candy Cane Fence',
	'Industrial Fence',
	'Iron Fence',
	'Obsidian Fence',
	'Stone Fence',
	'Wood Fence',
	'Fire Pit',
	'Iron Fire Pit',
	'Medieval Fireplace',
	'Blue Fireworks',
	'Red Fireworks',
	'Yellow Fireworks',
	'Haunted Fireworks',
	'Ghostly Flashlight',
	'Blue Adobe Floor',
	'Red Adobe Floor',
	'Yellow Adobe Floor',
	'Canyon Floor',
	'Industrial Floor',
	'Industrial Non-Skid Floor',
	'Industrial Wall',
	'Obsidian Brick Wall',
	'Galactic Floor',
	'Stone Floor',
	'Decorative Stone Floor',
	'Carved Stone Floor',
	'Wood Floor',
	'Decorative Wood Floor',
	'Haunted Floor',
	'Wood Wall',
	'Tile Wood Floor',
	'Autumnwood Flower',
	'Blue Flower',
	'Cactus Flower',
	'Wildwood Flower',
	'Red Flower',
	'Tundra Flower',
	'Weepwood Flower',
	'Wildflower',
	'Yellow Flower',
	'Fossils',
	'Figured Limestone Wall',
	'(lion fur / leather?)',
	'Candy Cane Gate',
	'Industrial Gate',
	'Iron Gate',
	'Obsidian Gate',
	'(stone gate?)',
	'Wood Gate',
	'Bronze Gauntlet Skin',
	'Diamond Mining Cell',
	'(mining cell prototype?)',
	'Golden Gauntlet Skin',
	'Iron Mining Cell',
	'Lumite Mining Cell',
	'The Hulking Hand',
	'Obsidian Mining Cell',
	'Silver Gauntlet Skin',
	'Stone Mining Cell',
	'Wood Mining Cell',
	'Industrial Gear',
	'Blue Gift Box',
	'Green Gift Box',
	'Red Gift Box',
	'Glass',
	'Reinforced Glass',
	'Diamond Glass',
	'Tourmaline Glass',
	'Green Tourmaline Glass',
	'Blue Stained Glass',
	'Red Stained Glass',
	'Yellow Stained Glass',
	'Glob of Goo',
	'Melted Wax',
	'Hidden Temple Goblet',
	'Grass',
	'Corrupted Grass',
	'Dead Grass',
	'Savannah Grass',
	'Tallgrass',
	'Savannah Tallgrass',
	'Haunted Gravestone',
	'Vlad-A-Rang',
	'Armor-Piercing Bomb',
	'(corrupt bomb prototype?)',
	'Fire Bomb',
	'Force Bomb',
	'Freeze Bomb',
	'Poison Bomb',
	'Corrupt Bomb',
	'Scare Flare',
	'Explosive Bomb',
	'Flaming Skull',
	'Stun Bomb',
	'Purification Bomb',
	'(grass variant?)',
	'Detritus',
	'Rocky Dirt',
	'Gunpowder',
	'Hardened Lava',
	'Holiday Pet Hat',
	'Calavera Cabeza',
	'(hoof?)',
	'(spiky pumpkin?)',
	'Horned Melon Seed',
	'Ice',
	'Ice Slope',
	'Glass Slope Inner Corner',
	'Haunted Idol',
	'Infused Haunted Idol',
	'Unleashed Haunted Idol',
	'Igneous Rock',
	'Iron Bar',
	'Tempered Iron Bar',
	'Questionable Jerky',
	'Industrial Ladder',
	'Galactic Ladder',
	'Stone Ladder',
	'Wood Ladder',
	'Blue Lamp',
	'Haunted Lamp',
	'Industrial Lamp',
	'Medieval Lamp',
	'Gas Lamp',
	'Red Lamp',
	'Wood Burning Lamp',
	'Yellow Lamp',
	'Arctek Lantern',
	'Grand Arctek Lantern',
	'Lava',
	'Ashenwood Leaves',
	'Mocha Autumnwood Leaves',
	'Cinnamon Autumnwood Leaves',
	'Citrus Autumnwood Leaves',
	'Corrupted Ashenwood Leaves',
	'Wildwood Leaves',
	'Dark Wildwood Leaves',
	'Cragwood Leaves',
	'Shorewood Leaves',
	'Parchwood Leaves',
	'(dark parchwood leaves?)',
	'Elderwood Leaves',
	'(snowy elderwood leaves?)',
	'(light shorewood leaves?)',
	'Weepwood Leaves',
	'Leafi Leaf',
	'Autumn Leafi Leaf',
	'Dried Leafi Leaf',
	'Mossy Leafi Leaf',
	'Leather',
	'(leather prototype?)',
	'(moss prototype?)',
	'LED',
	'Galactic LED',
	'Diamond Leggings',
	'Iron Leggings',
	'Leather Leggings',
	'Lumite Leggings',
	'Obsidian Leggings',
	'Crisphead Lettuce',
	'Lettuce Seed',
	'Candy Skull Candles',
	'Blue Candy Skull Candle',
	'Red Candy Skull Candle',
	'Yellow Candy Skull Candle',
	'Lilypad',
	'Limestone',
	'(ashenwood log?)',
	'Driftwood',
	'(wildwood log?)',
	'Cragwood Log',
	'(elderwood log?)',
	'Weepwood Log',
	'(mossy weepwood log?)',
	'Weathered Wood Wall',
	'Banded Weathered Wood Wall',
	'Mob Drop',
	'Lumite Bar',
	'(coal bar?)',
	'(extractor prototype?)',
	'Magnetite',
	'(map?)',
	'Hidden Temple Altar',
	'Hidden Temple Chest',
	'Horned Melon',
	'Arctic Miru Eye',
	'Miru Eye',
	'Molasses',
	'Mold',
	'Bedrock Wall',
	'Limestone Wall',
	'Blue Patterned Ceramic Wall',
	'Blue-Green Patterned Ceramic Wall',
	'Mosaic Moroccan Wall',
	'Star-Patterned Moroccan Wall',
	'Tiled Moroccan Wall',
	'Opalescent Ceramic Wall',
	'Moss',
	'(coal / peakstone prototype?)',
	'Mud',
	'Brown Mushroom',
	'Glowing Mushroom',
	'Red Mushroom',
	'Industrial Number Pad',
	'Obsidian Bar',
	'Square Obsidian Wall',
	'(triangles obsidian wall?)',
	'Rhombus Obsidian Wall',
	'Checkered Obsidian Wall',
	'Diamond Ore',
	'Iron Ore',
	'Lumite Ore',
	'Obsidian Ore',
	'(decorative stone floor?)',
	'Ornamental Stone Wall',
	'Ornamental Swirl Stone Wall',
	'Blue Party Hat',
	'Red Party Hat',
	'Yellow Party Hat',
	'Stone Path',
	'Decorative Stone Path',
	'Natural Stone Path',
	'Peakstone',
	'Pebble\'s Pebble',
	'Limestone Pedestal',
	'Figured Obsidian Wall',
	'Arome Chizzard',
	'Fantasia De Leafi',
	'Eau De Pigsy',
	'L\'Rockster',
	'Arc Picture Frame',
	'Picture Frame',
	'Pie',
	'Blazing Pie',
	'Corrupted Pie',
	'Frigid Pie',
	'Chizzard Pot Pie',
	'Melon Pie',
	'Mushroom Pot Pie',
	'Wholesome Pie',
	'Pigsy Droppings',
	'Feral Pigsy Fur',
	'(rocky grass?)',
	'Matted Needles',
	'Rimecone',
	'Placemat',
	'Flower Pot',
	'Grumm\'s Temple Garden',
	'(double wood planter?)',
	'Wood Planter',
	'(triple / quadruple wood planter?)',
	'Plow',
	'Basic Health Potion',
	'Golden Potion',
	'Bat Juice',
	'Health Regeneration Potion',
	'(basic health potion prototype?)',
	'Marigold Potion',
	'(corruption resistance potion prototype?)',
	'Corruption Resistance Potion',
	'Fire Resistance Potion',
	'Freeze Resistance Potion',
	'Poison Resistance Potion',
	'Advanced Health Potion',
	'Speed Potion',
	'Industrial LED',
	'Haunted Pumpkin',
	'Rambeau Tuft',
	'(mob drop prototype?)',
	'(backpack prototype?)',
	'Paper (Common Recipe)',
	'Scroll (Rare Recipe)',
	'Book (Uncommon Recipe)',
	'Reeds',
	'Trog Horn',
	'Rockster Rock',
	'Diamond Rod',
	'Iron Rod',
	'Lumite Rod',
	'Obsidian Rod',
	'Stone Rod',
	'Blue Adobe Slope',
	'Blue Clay Slope Inner Corner',
	'Blue Clay Slope Outer Corner',
	'(adobe / clay slope?)',
	'Red Adobe Slope',
	'Red Clay Slope Inner Corner',
	'Red Clay Slope Outer Corner',
	'Adobe Slope',
	'White Clay Slope Inner Corner',
	'White Clay Slope Outer Corner',
	'Yellow Adobe Slope',
	'Yellow Clay Slope Inner Corner',
	'Yellow Clay Slope Outer Corner',
	'Bedrock Slope',
	'Bedrock Slope Inner Corner',
	'Bedrock Slope Outer Corner',
	'Bungalow Roof',
	'Bungalow Roof Inner Corner',
	'Bungalow Roof Outer Corner',
	'Blue Adobe Roof',
	'Blue Adobe Roof Inner Corner',
	'Blue Adobe Roof Outer Corner',
	'Red Adobe Roof',
	'Red Adobe Roof Inner Corner',
	'Red Adobe Roof Outer Corner',
	'Yellow Adobe Roof',
	'Yellow Adobe Roof Inner Corner',
	'Yellow Adobe Roof Outer Corner',
	'Copper Roof',
	'Copper Roof Inner Corner',
	'Copper Roof Outer Corner',
	'Diamond Roof',
	'Diamond Roof Inner Corner',
	'Diamond Roof Outer Corner',
	'Dirt Slope',
	'Dirt Slope Inner Corner',
	'Dirt Slope Outer Corner',
	'Igneous Roof',
	'Igneous Roof Inner Corner',
	'Igneous Roof Outer Corner',
	'Gingerbread Roof',
	'Gingerbread Roof Inner Corner',
	'Gingerbread Roof Outer Corner',
	'Glass Slope',
	'Glass Slope Inner Corner',
	'Glass Slope Outer Corner',
	'Grass Slope',
	'Grass Slope Inner Corner',
	'Grass Slope Outer Corner',
	'Haunted Roof',
	'Haunted Roof Inner Corner',
	'Haunted Roof Outer Corner',
	'Wafer Gingerbread Roof',
	'Wafer Gingerbread Roof Inner Corner',
	'Wafer Gingerbread Roof Outer Corner',
	'Iron Roof',
	'Iron Roof Inner Corner',
	'Iron Roof Outer Corner',
	'Limestone Slope',
	'Limestone Slope Inner Corner',
	'Limestone Slope Outer Corner',
	'Lumite Roof',
	'Lumite Roof Inner Corner',
	'Lumite Roof Outer Corner',
	'Hidden Temple Roof',
	'Hidden Temple Roof Inner Corner',
	'Hidden Temple Roof Outer Corner',
	'Medieval Roof',
	'Medieval Roof Inner Corner',
	'Medieval Roof Outer Corner',
	'Obsidian Roof',
	'Obsidian Roof Inner Corner',
	'Obsidian Roof Outer Corner',
	'Patina Roof',
	'Patina Roof Inner Corner',
	'Patina Roof Outer Corner',
	'Peakstone Slope',
	'Peakstone Slope Inner Corner',
	'Peakstone Slope Outer Corner',
	'Limestone Roof',
	'Limestone Roof Inner Corner',
	'Limestone Roof Outer Corner',
	'Stone Roof',
	'Stone Roof Inner Corner',
	'Stone Roof Outer Corner',
	'Thatched Roof',
	'Slanted Straw Roof Inner Corner',
	'Slanted Straw Roof Outer Corner',
	'Tin Roof',
	'Tin Roof Inner Corner',
	'Tin Roof Outer Corner',
	'Wood Roof',
	'Wood Roof Inner Corner',
	'Wood Roof Outer Corner',
	'(wood block prototype?)',
	'(wood block prototype?)',
	'Salt',
	'(some adobe block?)',
	'Saltrock',
	'Sand',
	'Smooth Sandstone',
	'Sandstone',
	'Blazing Sandwich',
	'Bog Sandwich',
	'Corrupted Sandwich',
	'Egg Sandwich',
	'Frigid Sandwich',
	'Jerky Sandwich',
	'Melon Sandwich',
	'Mushroom Sandwich',
	'Tar Sandwich',
	'Turnip Sandwich',
	'Sandwich',
	'Wholesome Sandwich',
	'Ashenwood Sapling',
	'Cragwood Sapling',
	'Elderwood Sapling',
	'Seashells',
	'Industrial Table',
	'Diamond Pauldron',
	'Iron Pauldron',
	'Leather Pauldron',
	'Lumite Pauldron',
	'Obsidian Pauldron',
	'Shrewdshrew Tail',
	'(grass / moss prototype?)',
	'(emerald block?)',
	'Shrub',
	'Corrupt Obelisk',
	'Stone Sign',
	'Hanging Stone Sign',
	'Wood Sign',
	'Siltstone',
	'Sinew',
	'Blue Adobe Slab',
	'(adobe slab?)',
	'Red Adobe Slab',
	'Adobe Slab',
	'Yellow Adobe Slab',
	'Bedrock Slab',
	'Diamond Slab',
	'Dirt Slab',
	'Glass Slab',
	'Grass Slab',
	'Iron Slab',
	'Limestone Slab',
	'Lumite Slab',
	'Obsidian Slab',
	'Peakstone Slab',
	'Galactic Slab',
	'Galactic Hull Slab',
	'Stone Slab',
	'Wood Slab',
	'Reinforced Glass Slope',
	'Reinforced Glass Slope Inner Corner',
	'Reinforced Glass Slope Outer Corner',
	'Galactic Rounded Slope',
	'Galactic Striped Wall Slope',
	'Galactic Hull Slope',
	'Galactic Hull Slope Inner Corner',
	'Galactic Hull Slope Outer Corner',
	'Galactic Pipes',
	'Snow',
	'(plowed snow?)',
	'Snowcube',
	'Snowcap',
	'Blazing Soup',
	'Bog Broth',
	'Corrupted Soup',
	'Egg Drop Soup',
	'Frigid Soup',
	'Chizzard Noodle Soup',
	'Tar Soup',
	'Soup',
	'Wholesome Soup',
	'(faded green spiky block?)',
	'(purple corruption spiky block?)',
	'(azure air bubbles spiky block?)',
	'(yellow flame spiky block?)',
	'(white snowflake spiky block?)',
	'(orange red heart spiky block?)',
	'(light yellow compass spiky block?)',
	'(cyan upwards arrow spiky block?)',
	'(white feather spiky block?)',
	'(yellow lightning spiky block?)',
	'Blue Adobe Stairs',
	'Blue Clay Stairs Inner Corner',
	'Blue Clay Stairs Outer Corner',
	'(brown adobe stairs?)',
	'Red Adobe Stairs',
	'Red Clay Stairs Inner Corner',
	'Red Clay Stairs Outer Corner',
	'Adobe Stairs',
	'White Clay Stairs Inner Corner',
	'White Clay Stairs Outer Corner',
	'Yellow Adobe Stairs',
	'Yellow Clay Stairs Inner Corner',
	'Yellow Clay Stairs Outer Corner',
	'Bedrock Stairs',
	'Bedrock Stairs Inner Corner',
	'Bedrock Stairs Outer Corner',
	'Bungalow Stairs',
	'Bungalow Stairs Inner Corner',
	'Bungalow Stairs Outer Corner',
	'Diamond Stairs',
	'Diamond Stairs Inner Corner',
	'Diamond Stairs Outer Corner',
	'Dirt Stairs',
	'Dirt Stairs Inner Corner',
	'Dirt Stairs Outer Corner',
	'Gingerbread Stairs',
	'Gingerbread Stairs Inner Corner',
	'Gingerbread Stairs Outer Corner',
	'Glass Stairs',
	'Glass Stairs Inner Corner',
	'Glass Stairs Outer Corner',
	'Grass Stairs',
	'Grass Stairs Inner Corner',
	'Grass Stairs Outer Corner',
	'Haunted Stairs',
	'Carpeted Haunted Stairs',
	'Haunted Stairs Inner Corner',
	'Haunted Stairs Outer Corner',
	'Industrial Stairs',
	'Iron Stairs',
	'Iron Stairs Inner Corner',
	'Iron Stairs Outer Corner',
	'Limestone Stairs',
	'Limestone Stairs Inner Corner',
	'Limestone Stairs Outer Corner',
	'Lumite Stairs',
	'Lumite Stairs Inner Corner',
	'Lumite Stairs Outer Corner',
	'Hidden Temple Stairs',
	'Hidden Temple Stairs Inner Corner',
	'Hidden Temple Stairs Outer Corner',
	'Medieval Carpeted Stairs',
	'Medieval Stairs',
	'Medieval Stairs Inner Corner',
	'Medieval Stairs Outer Corner',
	'Obsidian Stairs',
	'Obsidian Stairs Inner Corner',
	'Obsidian Stairs Outer Corner',
	'Peakstone Stairs',
	'Peakstone Stairs Inner Corner',
	'Peakstone Stairs Outer Corner',
	'Galactic Stairs',
	'Stone Stairs',
	'Stone Stairs Inner Corner',
	'Stone Stairs Outer Corner',
	'Wood Stairs',
	'Wood Stairs Inner Corner',
	'Wood Stairs Outer Corner',
	'Stalactite',
	'(crafting table?)',
	'Cooking Station',
	'Forge',
	'(gray pink station?)',
	'Processor',
	'Twig',
	'Wood Rod',
	'Stone',
	'Canyonstone',
	'Dark Canyonstone',
	'Ruddy Canyonstone',
	'Corrupted Stone',
	'(fossils block?)',
	'Wood Stool',
	'(sulfur block?)',
	'Sulfur',
	'Industrial Lever',
	'Industrial Switch',
	'Medieval Switch',
	'Galactic Terminal',
	'(silver sword?)',
	'Crypt Cutter',
	'Industrial Crowbar',
	'Diamond Sword',
	'Golden Sword',
	'Iron Sword',
	'Lumite Sword',
	'Hidden Temple Sword',
	'Medieval Sword',
	'Obsidian Sword',
	'Galactic Flux Incapacitator',
	'The Grim Reaper',
	'Stone Sword',
	'Rainbownator 5000',
	'Wood Sword',
	'Arctek Table',
	'Advanced Arctek Table',
	'Grand Arctek Table',
	'Diamond Table',
	'Iron Table',
	'Lumite Table',
	'Hidden Temple Table',
	'Medieval Table',
	'Obsidian Table',
	'Stone Table',
	'Wood Table',
	'(arctek LED?)',
	'Tar',
	'Teleporter',
	'Hidden Temple Throne',
	'Medieval Throne',
	'Super TNT',
	'Advanced TNT',
	'TNT',
	'Strong TNT',
	'Top Hat',
	'Blue Top Hat',
	'Pumpkiru\'s Top Hat',
	'Red Top Hat',
	'Yellow Top Hat',
	'Arctek Torch',
	'Grand Arctek Torch',
	'Bungalow Torch',
	'Coal Torch',
	'Blue Holiday Light',
	'Green Holiday Light',
	'Red Holiday Light',
	'Yellow Holiday Light',
	'Wide Industrial Light',
	'Industrial Light',
	'Hidden Temple Torch',
	'Medieval Torch',
	'Moss Torch',
	'Galactic Lamp',
	'(torn journal page / crumpled note?)',
	'Touchstone',
	'Tourmaline',
	'Hidden Temple Trap Door',
	'Stone Trap Door',
	'Wood Trap Door',
	'Rustic Trap Door',
	'Trog Horn',
	'Turnip',
	'Turnip Seed',
	'Twine',
	'Rainbownator 5000',
	'Industrial Vent',
	'Vines',
	'(cragwood with vines?)',
	'(wood chips / swarf block?)',
	'Adobe Bricks',
	'Blue Adobe Wall',
	'Adobe Wall',
	'Red Adobe Wall',
	'Yellow Adobe Wall',
	'Haunted Stone Wall',
	'Haunted Wall',
	'Bungalow Wall',
	'Bungalow Accent Wall',
	'Bungalow Fur Wall',
	'Bungalow Support',
	'Candy Cane Wall',
	'Cobblestone',
	'Mossy Cobblestone',
	'Copper Wall',
	'Corrupted Stone Wall',
	'(corrupted stone wall?)',
	'Octagon Diamond Wall',
	'Star Diamond Wall',
	'Square Diamond Wall',
	'Hardened Lava Floor',
	'Igneous Wall',
	'Crossed Furnace Wall',
	'Aztec Furnace Wall',
	'Grated Furnace Wall',
	'(gingerbread wall?)',
	'Brick Gingerbread Wall',
	'Tiled Gingerbread Wall',
	'Swirl Gingerbread Wall',
	'Golden Wall',
	'Banded Golden Wall',
	'Studded Golden Wall',
	'Banded Golden Wall',
	'Studded Golden Wall',
	'Hardened Lava Wall',
	'Hardened Lava Inlay Wall',
	'Stacked Hardened Lava Wall',
	'(igneous wall?)',
	'(medieval brick wall?)',
	'Industrial Grated Wall',
	'(aztec wall?)',
	'Lumite Wall',
	'Dark Lumite Wall',
	'Shattered Dark Lumite Wall',
	'Shattered Lumite Wall',
	'Shattered Light Lumite Wall',
	'Light Lumite Wall',
	'Hidden Temple Serpent Accent',
	'Hidden Temple Accent',
	'Hidden Temple Wall',
	'Hidden Temple Trim',
	'Hidden Temple Glyph Wall',
	'Hidden Temple Turquoise Trim',
	'Medieval Brick Wall',
	'Medieval Banner Wall',
	'Medieval Crest Wall',
	'Medieval Brick Inset Wall',
	'Medieval Spike Wall',
	'(industrial/iron banded wall?)',
	'Iron Wall',
	'(iron wall?)',
	'Curl Iron Wall',
	'(siltstone wall?)',
	'Siltstone Wall',
	'Blue Mosaic Tile Wall',
	'Red Mosaic Tile Wall',
	'Yellow Mosaic Tile Wall',
	'Square Obsidian Wall',
	'Checkered Obsidian Wall',
	'Rhombus Obsidian Wall',
	'(some other obsidian wall?)',
	'Patina Wall',
	'Stone Plaque',
	'Wood Plaque',
	'Bedrock Wall',
	'Limestone Wall',
	'Carved Limestone Wall',
	'Chiseled Limestone Laurel Accent',
	'Chiseled Limestone Spiral Accent',
	'Chiseled Limestone Column',
	'(limestone pedestal / column prototype?)',
	'(limestone wall?)',
	'(limestone wall?)',
	'Sand Castle Wall',
	'Galactic Wall',
	'Galactic Hull',
	'Stone Wall Shelf',
	'Stone Block Wall',
	'Stone Boulder Wall',
	'Stacked Stone Wall',
	'(yellow rough concrete?)',
	'(dark red rough concrete?)',
	'(red rough concrete?)',
	'Thatched Wall',
	'Tin Wall',
	'Haunted Wall',
	'(wood wall?)',
	'Blue Wood Wall',
	'Decorative Wood Wall',
	'Wood Gravel Wall',
	'Red Wood Wall',
	'Yellow Wood Wall',
	'Warmworm Tooth',
	'Washer',
	'Water',
	'Bog Water',
	'Corrupted Water',
	'(water?)',
	'Mineral Water',
	'(mineral water?)',
	'Weeds',
	'Wheat',
	'Wheat Seed',
	'Bungalow Window',
	'Gingerbread Window',
	'Industrial Window',
	'(reinforced glass prototype?)',
	'Galactic Porthole',
	'Stucco Window',
	'Dark Stucco Window',
	'Ruddy Stucco Window',
	'Wood Window',
	'Barred Wood Window',
	'Stone Window',
	'Barred Window',
	'Ashenwood',
	'Autumnwood',
	'Corrupted Wood',
	'Cragwood',
	'Shorewood',
	'Shorewood Husk',
	'(autumnwood / elderwood?)',
	'Elderwood',
	'Wildwood',
	'Wildwood Vines',
	'Weepwood',
	'Weepwood Vines',
];